parameters:
#    real_real_estate.example.class: Real\RealEstateBundle\Example

services:
#    real_real_estate.example:
#        class: %real_real_estate.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
